import { spawn } from "node:child_process";
import { err, fromPromise, ok, type Result } from "neverthrow";
import { normalizeError, normalizeErrorMessage } from "./errors.js";
import { withRetry, type RetryOptions } from "./retry.js";
import type { TrackEntry } from "./types.js";

type NicoAuth = {
  niconicoUser?: string;
  niconicoPassword?: string;
  /**
   * Path to a Netscape-format cookies.txt produced from the NicoNico
   * `user_session` cookie. When present it takes precedence over
   * username/password because cookie auth survives 2FA and the broken
   * yt-dlp password login flow.
   */
  cookiesPath?: string;
};

const VIDEO_ID_PREFIXES = [
  "sm",
  "nm",
  "so",
  "ax",
  "yo",
  "nl",
  "ig",
  "na",
  "cw",
  "zb",
  "z9",
] as const;

class RetriableHttpError extends Error {
  constructor(
    readonly status: number,
    readonly retryAfterMs?: number,
  ) {
    super(`Tag search API returned ${status}.`);
  }
}

class YtDlpCommandError extends Error {
  constructor(
    readonly exitCode: number,
    readonly stderr: string,
  ) {
    super(
      `yt-dlp exited with code ${exitCode}: ${stderr || "no stderr output"}`,
    );
  }
}

/**
 * Build a Netscape-format cookies.txt body from a NicoNico `user_session`
 * cookie value. Accepts either the raw value (`user_session_…`) or a
 * `name=value` pair pasted from devtools. Returns undefined when empty.
 */
export function buildNiconicoCookieFile(session: string): string | undefined {
  let value = session.trim();

  if (!value) {
    return undefined;
  }

  // Tolerate "user_session=user_session_…" or a full "Cookie:" header paste.
  value = value.replace(/^cookie:\s*/i, "");
  const sessionMatch = value.match(/user_session=([^;\s]+)/i);

  if (sessionMatch) {
    value = sessionMatch[1];
  }

  // Far-future expiry so yt-dlp does not treat the cookie as a session cookie.
  const expiry = 2147483647;

  return [
    "# Netscape HTTP Cookie File",
    "# Generated by NicomusicBot. Do not edit.",
    [".nicovideo.jp", "TRUE", "/", "TRUE", expiry, "user_session", value].join(
      "\t",
    ),
    "",
  ].join("\n");
}

export function authArgs(auth: NicoAuth): string[] {
  if (auth.cookiesPath) {
    return ["--cookies", auth.cookiesPath];
  }

  if (auth.niconicoUser && auth.niconicoPassword) {
    return [
      "--username",
      auth.niconicoUser,
      "--password",
      auth.niconicoPassword,
    ];
  }

  return [];
}

async function runCommand(
  command: string,
  args: string[],
): Promise<
  Result<{ stdout: string; stderr: string; exitCode: number }, Error>
> {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";

    child.stdout?.setEncoding("utf8");
    child.stderr?.setEncoding("utf8");
    child.stdout?.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      resolve(err(new Error(`Failed to spawn "${command}": ${error.message}`)));
    });
    child.on("close", (exitCode) => {
      resolve(
        ok({
          stdout,
          stderr,
          exitCode: exitCode ?? -1,
        }),
      );
    });
  });
}

function isVideoId(value: string): boolean {
  const normalized = value.trim().toLowerCase();

  return (
    VIDEO_ID_PREFIXES.some((prefix) => normalized.startsWith(prefix)) &&
    /^\d+$/.test(normalized.slice(2))
  );
}

function stripWrappingBrackets(input: string): string {
  return input.trim().replace(/^<|>$/g, "");
}

export function normalizeNiconicoUrl(input: string): string {
  let url = stripWrappingBrackets(input);

  if (!url) {
    return url;
  }

  if (/^https?:\/\/nico\.ms\//i.test(url)) {
    url = url.split("://", 2)[1] ?? url;
  }

  if (isVideoId(url)) {
    return `https://www.nicovideo.jp/watch/${url.toLowerCase()}`;
  }

  if (/^nico\.ms\//i.test(url)) {
    const path = url.slice("nico.ms/".length);

    if (isVideoId(path)) {
      return `https://www.nicovideo.jp/watch/${path.toLowerCase()}`;
    }

    return `https://www.nicovideo.jp/${path}`;
  }

  url = url.replace(/:\/\/sp\.nicovideo\.jp/i, "://www.nicovideo.jp");

  if (/^sp\.nicovideo\.jp/i.test(url)) {
    return `https://www.${url.slice("sp.".length)}`;
  }

  if (!/^https?:\/\//i.test(url)) {
    if (/^nicovideo\.jp/i.test(url)) {
      return `https://www.${url}`;
    }

    return `https://${url}`;
  }

  if (/^https?:\/\/nicovideo\.jp/i.test(url)) {
    return url.replace(/:\/\/nicovideo\.jp/i, "://www.nicovideo.jp");
  }

  return url;
}

export function makeTrackUrl(entry: TrackEntry): string | undefined {
  const value = entry.id ?? entry.url ?? entry.webpageUrl;

  if (!value) {
    return undefined;
  }

  return normalizeNiconicoUrl(value);
}

async function runYtDlpJson(
  args: string[],
): Promise<Result<TrackEntry[], Error>> {
  const result = await fromPromise(
    withRetry(
      async () => {
        const commandResult = await runCommand("yt-dlp", args);

        if (commandResult.isErr()) {
          throw commandResult.error;
        }

        if (
          commandResult.value.exitCode !== 0 &&
          !commandResult.value.stdout.trim()
        ) {
          throw new YtDlpCommandError(
            commandResult.value.exitCode,
            commandResult.value.stderr.trim(),
          );
        }

        return commandResult.value;
      },
      {
        attempts: 3,
        shouldRetry: isTransientYtDlpError,
      },
    ),
    normalizeError,
  );

  if (result.isErr()) {
    return err(result.error);
  }

  if (result.value.exitCode !== 0 && !result.value.stdout.trim()) {
    return err(
      new YtDlpCommandError(result.value.exitCode, result.value.stderr.trim()),
    );
  }

  const entries = result.value.stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .flatMap((line) => {
      try {
        const parsed = JSON.parse(line) as Record<string, unknown>;

        return [
          {
            id: typeof parsed.id === "string" ? parsed.id : undefined,
            title: typeof parsed.title === "string" ? parsed.title : undefined,
            url: typeof parsed.url === "string" ? parsed.url : undefined,
            webpageUrl:
              typeof parsed.webpage_url === "string"
                ? parsed.webpage_url
                : undefined,
          } satisfies TrackEntry,
        ];
      } catch {
        return [];
      }
    });

  return ok(entries);
}

function parseRetryAfterMs(response: Response): number | undefined {
  const retryAfter = response.headers.get("retry-after");

  if (!retryAfter) {
    return undefined;
  }

  const seconds = Number.parseFloat(retryAfter);

  if (Number.isFinite(seconds)) {
    return Math.max(0, seconds * 1_000);
  }

  const date = Date.parse(retryAfter);

  if (Number.isNaN(date)) {
    return undefined;
  }

  return Math.max(0, date - Date.now());
}

function isTransientHttpStatus(status: number): boolean {
  return status === 408 || status === 429 || status >= 500;
}

function messageIncludesAny(message: string, needles: string[]): boolean {
  return needles.some((needle) => message.includes(needle));
}

function isTransientFetchError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const message = error.message.toLowerCase();

  return (
    error instanceof TypeError ||
    messageIncludesAny(message, [
      "fetch failed",
      "network",
      "timeout",
      "timed out",
      "connection reset",
      "econnreset",
      "etimedout",
      "eai_again",
    ])
  );
}

function isTransientYtDlpError(error: unknown): boolean {
  if (!(error instanceof Error)) {
    return false;
  }

  const message =
    error instanceof YtDlpCommandError
      ? error.stderr.toLowerCase()
      : error.message.toLowerCase();

  if (messageIncludesAny(message, ["enoent", "eacces"])) {
    return false;
  }

  return messageIncludesAny(message, [
    "http error 408",
    "http error 429",
    "http error 5",
    "timed out",
    "timeout",
    "temporarily unavailable",
    "connection reset",
    "econnreset",
    "etimedout",
    "eai_again",
  ]);
}

async function fetchTagSearchResponse(
  url: URL,
  retryOptions: RetryOptions,
): Promise<Response> {
  return withRetry(
    async () => {
      const response = await fetch(url, {
        headers: {
          "User-Agent": "NicomusicBotCLI/0.1.0",
        },
      });

      if (isTransientHttpStatus(response.status)) {
        throw new RetriableHttpError(
          response.status,
          parseRetryAfterMs(response),
        );
      }

      return response;
    },
    {
      attempts: 3,
      ...retryOptions,
      shouldRetry:
        retryOptions.shouldRetry ??
        ((error) =>
          error instanceof RetriableHttpError || isTransientFetchError(error)),
      getDelayMs:
        retryOptions.getDelayMs ??
        ((error) =>
          error instanceof RetriableHttpError ? error.retryAfterMs : undefined),
    },
  );
}

export async function fetchEntries(
  url: string,
  auth: NicoAuth,
): Promise<TrackEntry[]> {
  const baseArgs = ["--dump-json", "-q", "--ignore-errors", ...authArgs(auth)];
  let entriesResult = await runYtDlpJson([
    ...baseArgs,
    "--flat-playlist",
    normalizeNiconicoUrl(url),
  ]);

  if (entriesResult.isErr() || entriesResult.value.length === 0) {
    entriesResult = await runYtDlpJson([
      ...baseArgs,
      normalizeNiconicoUrl(url),
    ]);
  }

  if (entriesResult.isErr()) {
    throw entriesResult.error;
  }

  return entriesResult.value;
}

export async function resolveTrackTitle(
  entry: TrackEntry,
  auth: NicoAuth,
): Promise<string | undefined> {
  if (entry.title && !isVideoId(entry.title)) {
    return entry.title;
  }

  const url = makeTrackUrl(entry);

  if (!url) {
    return entry.title;
  }

  const metadataResult = await runYtDlpJson([
    "--dump-json",
    "-q",
    "--no-playlist",
    ...authArgs(auth),
    url,
  ]);

  if (metadataResult.isErr()) {
    return entry.title;
  }

  return metadataResult.value[0]?.title ?? entry.title;
}

function extractTagFromInput(input: string): string {
  const cleaned = stripWrappingBrackets(input);

  if (!cleaned.includes("/tag/")) {
    return cleaned;
  }

  const tagPath = cleaned.split("/tag/", 2)[1]?.split("?", 1)[0] ?? cleaned;

  try {
    return decodeURIComponent(tagPath);
  } catch {
    return tagPath;
  }
}

export function parseTagRequest(raw: string): { tag: string; limit: number } {
  const tokens = raw.trim().split(/\s+/).filter(Boolean);
  let limit = 30;

  if (tokens.length > 1) {
    const maybeLimit = tokens.at(-1);

    if (maybeLimit && /^\d+$/.test(maybeLimit)) {
      limit = Number.parseInt(maybeLimit, 10);
      tokens.pop();
    }
  }

  return {
    tag: extractTagFromInput(tokens.join(" ")),
    limit: Math.max(1, Math.min(limit || 30, 100)),
  };
}

export async function searchByTag(
  tagInput: string,
  limit: number,
  retryOptions: RetryOptions = {},
): Promise<TrackEntry[]> {
  const tag = extractTagFromInput(tagInput);
  const url = new URL(
    "https://snapshot.search.nicovideo.jp/api/v2/snapshot/video/contents/search",
  );

  url.search = new URLSearchParams({
    q: tag,
    targets: "tags",
    fields: "contentId,title",
    _sort: "-startTime",
    _limit: String(Math.max(1, Math.min(limit, 100))),
    _context: "NicomusicBotCLI",
  }).toString();

  const responseResult = await fromPromise(
    fetchTagSearchResponse(url, retryOptions),
    (error) =>
      new Error(`Tag search request failed: ${normalizeErrorMessage(error)}`),
  );

  if (responseResult.isErr()) {
    throw responseResult.error;
  }

  const response = responseResult.value;

  if (!response.ok) {
    throw new Error(`Tag search API returned ${response.status}.`);
  }

  const jsonResult = await fromPromise(
    response.json(),
    (error) =>
      new Error(
        `Failed to decode tag search response: ${normalizeErrorMessage(error)}`,
      ),
  );

  if (jsonResult.isErr()) {
    throw jsonResult.error;
  }

  const data = jsonResult.value as {
    data?: Array<{
      contentId?: string;
      title?: string;
    }>;
  };

  return (data.data ?? []).flatMap((item) => {
    if (!item.contentId) {
      return [];
    }

    return [
      {
        id: item.contentId,
        title: item.title ?? item.contentId,
      } satisfies TrackEntry,
    ];
  });
}
